pipeline {

	agent any

	environment {
		MAVEN_OPTS = "-Dmaven.repo.local=${env.WORKSPACE}/.m2"
	}

	stages {

		stage('Checkout') {
			steps {
				checkout scm
			}
		}

		stage('Build') {
			steps {
				sh 'mvn clean compile'
			}
			post {
				success {
					echo "Compilation réussie"
				}
				failure {
					echo "Erreur lors de la compilation"
				}
			}
		}

		stage('Tests') {
			steps  {
				sh 'mvn test'
			}
			post {
				success {
					echo "Tests réussis"
				}
				failure {
					echo "Tests  échoués"
				}
			}
		}

	}

	post {
		always {
			echo "Fin de la phase CI"
		}
	}

}